/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cake;

import cake.graphics.TetrisWindow;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());

        new TetrisWindow();
    }
}
